import { Record } from "./types";

export const records: Record[] = [
  {
    id: 1,
    name: "Bridges to Babylon",
    artist: "The Rolling Stones",
    coverUrl: "/images/covers/bridges-to-babylon.webp",
    type: "vinyl",
    price: 21.99,
    originalPrice: 21.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 2,
    name: "Sueño su boca",
    artist: "Raúl",
    coverUrl: "/images/covers/sueno-su-boca.webp",
    type: "vinyl",
    price: 99.99,
    originalPrice: 119.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 3,
    name: "Temple of the Dog",
    artist: "Temple of the Dog",
    coverUrl: "/images/covers/temple-of-the-dog.webp",
    type: "digital",
    price: 23.99,
    originalPrice: 23.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 4,
    name: "Whenever you need somebody",
    artist: "Rick Astley",
    coverUrl: "/images/covers/whenever-you-need-somebody.webp",
    type: "digital",
    price: 269.99,
    originalPrice: 359.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 5,
    name: "Marifé de Triana",
    artist: "Marifé de Triana",
    coverUrl: "/images/covers/marife-de-triana.webp",
    type: "vinyl",
    price: 219.99,
    originalPrice: 219.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 6,
    name: "Show me love",
    artist: "Robin S",
    coverUrl: "/images/covers/showm-me-love.webp",
    type: "digital",
    price: 19.99,
    originalPrice: 19.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 7,
    name: "Homework",
    artist: "Daft Punk",
    coverUrl: "/images/covers/homework.webp",
    type: "vinyl",
    price: 24.59,
    originalPrice: 24.59,
    isRecordOfTheMonth: true,
  },
  {
    id: 8,
    name: "El Chiringuito",
    artist: "Georgie Dann",
    coverUrl: "/images/covers/el-chiringuito.webp",
    type: "vinyl",
    price: 1.99,
    originalPrice: 1.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 9,
    name: "Deep Purple in Rock",
    artist: "Deep Purple",
    coverUrl: "/images/covers/deep-purple-in-rock.webp",
    type: "vinyl",
    price: 27.49,
    originalPrice: 27.49,
    isRecordOfTheMonth: false,
  },
  {
    id: 10,
    name: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    coverUrl: "/images/covers/led-zeppelin-iv.webp",
    type: "vinyl",
    price: 34.99,
    originalPrice: 34.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 11,
    name: "Raro",
    artist: "El Cuarteto de Nos",
    coverUrl: "/images/covers/raro.webp",
    type: "digital",
    price: 19.99,
    originalPrice: 39.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 12,
    name: "De paso / Libertad",
    artist: "Luis Eduardo Aute",
    coverUrl: "/images/covers/de-paso-libertad.webp",
    type: "digital",
    price: 23.99,
    originalPrice: 23.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 13,
    name: "Agila",
    artist: "Extremoduro",
    coverUrl: "/images/covers/agila.webp",
    type: "vinyl",
    price: 59.99,
    originalPrice: 70.99,
    isRecordOfTheMonth: false,
  },
  {
    id: 14,
    name: "Un día en el mundo",
    artist: "Vetusta morla",
    coverUrl: "/images/covers/un-dia-en-el-mundo.webp",
    type: "digital",
    price: 19.99,
    originalPrice: 19.99,
    isRecordOfTheMonth: false,
  },
];
