import { Record } from "./types";

const records: Record[] = [
  {
    id: 1,
    name: "Bridges to Babylon",
    artist: "The Rolling Stones",
    coverUrl: "/public/multimedia/img/Bridges-to-Babylon.jpg",
    type: "vinyl",
    price: 21.99,
    originalPrice: 21.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 2,
    name: "Sueño su boca",
    artist: "Raúl",
    coverUrl: "/public/multimedia/img/Sueño-su-boca.jpg",
    type: "vinyl",
    price: 99.99,
    originalPrice: 119.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 3,
    name: "Temple of the Dog",
    artist: "Temple of the Dog",
    coverUrl: "/public/multimedia/img/Temple-of-the-Dog.jpg",
    type: "digital",
    price: 23.99,
    originalPrice: 23.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 4,
    name: "Whenever you need somebody",
    artist: "Rick Astley",
    coverUrl: "/public/multimedia/img/Whenever-you-need-somebody.jpg",
    type: "digital",
    price: 269.99,
    originalPrice: 359.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 5,
    name: "Marifé de Triana",
    artist: "Marifé de Triana",
    coverUrl: "/public/multimedia/img/Marifé-de-Triana.jpg",
    type: "vinyl",
    price: 219.99,
    originalPrice: 219.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 6,
    name: "Show me love",
    artist: "Robin S",
    coverUrl: "/public/multimedia/img/Show-me-love.jpg",
    type: "digital",
    price: 19.99,
    originalPrice: 19.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 7,
    name: "Homework",
    artist: "Daft Punk",
    coverUrl: "/public/multimedia/img/Homework.jpg",
    type: "vinyl",
    price: 24.59,
    originalPrice: 24.59,
    isDiskOfTheMonth: true,
  },
  {
    id: 8,
    name: "El Chiringuito",
    artist: "Georgie Dann",
    coverUrl: "/public/multimedia/img/El-chiringuito.jpg",
    type: "vinyl",
    price: 1.99,
    originalPrice: 1.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 9,
    name: "Deep Purple in Rock",
    artist: "Deep Purple",
    coverUrl: "/public/multimedia/img/Deep-purple-in-Rock.jpg",
    type: "vinyl",
    price: 27.49,
    originalPrice: 27.49,
    isDiskOfTheMonth: false,
  },
  {
    id: 10,
    name: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    coverUrl: "/public/multimedia/img/Led-Zeppelin-IV.jpg",
    type: "vinyl",
    price: 34.99,
    originalPrice: 34.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 11,
    name: "Raro",
    artist: "El Cuarteto de Nos",
    coverUrl: "/public/multimedia/img/Raro.jpg",
    type: "digital",
    price: 19.99,
    originalPrice: 39.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 12,
    name: "De paso / Libertad",
    artist: "Luis Eduardo Aute",
    coverUrl: "/public/multimedia/img/De-paso-Libertad.jpg",
    type: "digital",
    price: 23.99,
    originalPrice: 23.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 13,
    name: "Agila",
    artist: "Extremoduro",
    coverUrl: "/public/multimedia/img/De-paso-Libertad.jpg",
    type: "vinyl",
    price: 59.99,
    originalPrice: 70.99,
    isDiskOfTheMonth: false,
  },
  {
    id: 14,
    name: "Un día en el mundo",
    artist: "Vetusta morla",
    coverUrl: "/public/multimedia/img/Un-dia-en-el-mundo.jpg",
    type: "digital",
    price: 19.99,
    originalPrice: 19.99,
    isDiskOfTheMonth: false,
  },
];
