import { Disk } from "./types";

const disks: Disk[] = [
  {
    id: "1",
    name: "Bridges to Babylon",
    artist: "The Rolling Stones",
    url: "/public/multimedia/img/Bridges-to-Babylon.jpg",
    type: "Vinyl",
    price: 21.99,
    originalPrice: 21.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "2",
    name: "Sueño su boca",
    artist: "Raúl",
    url: "/public/multimedia/img/Sueño-su-boca.jpg",
    type: "Vinyl",
    price: 99.99,
    originalPrice: 119.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "3",
    name: "Temple of the Dog",
    artist: "Temple of the Dog",
    url: "/public/multimedia/img/Temple-of-the-Dog.jpg",
    type: "Digital",
    price: 23.99,
    originalPrice: 23.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "4",
    name: "Whenever you need somebody",
    artist: "Rick Astley",
    url: "/public/multimedia/img/Whenever-you-need-somebody.jpg",
    type: "Digital",
    price: 269.99,
    originalPrice: 359.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "5",
    name: "Marifé de Triana",
    artist: "Marifé de Triana",
    url: "/public/multimedia/img/Marifé-de-Triana.jpg",
    type: "Vinyl",
    price: 219.99,
    originalPrice: 219.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "6",
    name: "Show me love",
    artist: "Robin S",
    url: "/public/multimedia/img/Show-me-love.jpg",
    type: "Digital",
    price: 19.99,
    originalPrice: 19.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "7",
    name: "Homework",
    artist: "Daft Punk",
    url: "/public/multimedia/img/Homework.jpg",
    type: "Vinyl",
    price: 24.59,
    originalPrice: 24.59,
    isDiskOfTheMonth: true,
  },
  {
    id: "8",
    name: "El Chiringuito",
    artist: "Georgie Dann",
    url: "/public/multimedia/img/El-chiringuito.jpg",
    type: "Vinyl",
    price: 1.99,
    originalPrice: 1.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "9",
    name: "Deep Purple in Rock",
    artist: "Deep Purple",
    url: "/public/multimedia/img/Deep-purple-in-Rock.jpg",
    type: "Vinyl",
    price: 27.49,
    originalPrice: 27.49,
    isDiskOfTheMonth: false,
  },
  {
    id: "10",
    name: "Led Zeppelin IV",
    artist: "Led Zeppelin",
    url: "/public/multimedia/img/Led-Zeppelin-IV.jpg",
    type: "Vinyl",
    price: 34.99,
    originalPrice: 34.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "11",
    name: "Raro",
    artist: "El Cuarteto de Nos",
    url: "/public/multimedia/img/Raro.jpg",
    type: "Digital",
    price: 19.99,
    originalPrice: 39.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "12",
    name: "De paso / Libertad",
    artist: "Luis Eduardo Aute",
    url: "/public/multimedia/img/De-paso-Libertad.jpg",
    type: "Digital",
    price: 23.99,
    originalPrice: 23.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "13",
    name: "Agila",
    artist: "Extremoduro",
    url: "/public/multimedia/img/De-paso-Libertad.jpg",
    type: "Vinyl",
    price: 59.99,
    originalPrice: 70.99,
    isDiskOfTheMonth: false,
  },
  {
    id: "14",
    name: "Un día en el mundo",
    artist: "Vetusta morla",
    url: "/public/multimedia/img/Un-dia-en-el-mundo.jpg",
    type: "Digital",
    price: 19.99,
    originalPrice: 19.99,
    isDiskOfTheMonth: false,
  },
];
